<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/jszip/jszip.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/pdfmake/pdfmake.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/pdfmake/vfs_fonts.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="<?= base_url("assets"); ?>/vendor/AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>